import turtle

t = turtle.Turtle()
t.speed(10)
t.width(2)

t.getscreen().colormode(255)
t.getscreen().bgcolor(224,246,238)

t.color(92,112,104)

# 2D L-system generated by Twitter's LSystemBot 2.0:
axiom = "HHQ"
rules = {"F":"[QN]F+F+", 
         "N":"[]++[HNQ]", 
         "Q":"[F[]QFH++N]",
         "H":"-FQNF[-]H"}
angle = 60
iterations = 6

def create_drawing(axiom, rules, angle, iterations):
    draw_str = axiom
    for generation in range(iterations):
        new_str = ""
        for char in draw_str:
            if ((char == "F") or (char == "N") or (char == "Q") or (char == "H")):
                new_str = new_str + rules[char]
            else:
                new_str = new_str + char
        draw_str = new_str

    stack = []
    for char in draw_str:
        if (char == "F"):
            t.forward(20)
        elif ((char == "N") or (char == "Q") or (char == "H")): # Dummy commands
            pass
        elif char == "+":
            t.right(angle)
        elif char == "-":
            t.left(angle)
        elif (char == "["): # Push the current position of the turtle
            pos = [t.xcor(), t.ycor()]
            a = t.heading()
            stack.append((pos, a))  
        else: # Pop the previous position of the turtle
            pos,a = stack.pop()
            t.penup()
            t.goto(pos[0], pos[1])
            t.setheading(a)
            t.pendown()

create_drawing(axiom, rules, angle, iterations)

turtle.done()
